import type {Song} from 'types';

export const songList: Song[] = [
  {
    id: 'TJ_77562',
    title: '거짓말',
    number: '77562',
    singer: '김승민(Feat.빅나티(서동현))',
    karaoke: 'TJ',
  },
  {
    id: 'TJ_77352',
    title: '첫사랑은거짓말이다',
    number: '77352',
    singer: '진민호',
    karaoke: 'TJ',
  },
  {
    id: 'TJ_95161',
    title: '거짓말이야',
    number: '95161',
    singer: '문소희',
    karaoke: 'TJ',
  },
  {
    id: 'TJ_76438',
    title: '사랑한단거짓말은안할래',
    number: '76438',
    singer: '먼데이키즈,V.O.S 최현준',
    karaoke: 'TJ',
  },
  {
    id: 'TJ_62824',
    title: '거짓말이라도해서널보고싶어',
    number: '62824',
    singer: '백지영',
    karaoke: 'TJ',
  },
  {
    id: 'TJ_75353',
    title: '거짓말이라도해서널보고싶어',
    number: '75353',
    singer: '백지영',
    karaoke: 'TJ',
  },
  {
    id: 'TJ_93944',
    title: '거짓말이라도해줘',
    number: '93944',
    singer: '크루셜스타(Feat.김이지)',
    karaoke: 'TJ',
  },
  {
    id: 'TJ_24094',
    title: '거짓말을해',
    number: '24094',
    singer: '세븐틴',
    karaoke: 'TJ',
  },
  {
    id: 'TJ_24063',
    title: '거짓말이네(멜로가체질OST)',
    number: '24063',
    singer: '유승우',
    karaoke: 'TJ',
  },
  {
    id: 'TJ_53536',
    title: '거짓말',
    number: '53536',
    singer: 'DK(디셈버)',
    karaoke: 'TJ',
  },
  {
    id: 'TJ_96020',
    title: '거짓없는사랑(Sincere Love)',
    number: '96020',
    singer: '설녹수',
    karaoke: 'TJ',
  },
  {
    id: 'TJ_98676',
    title: '거짓말이라도해봐',
    number: '98676',
    singer: '서제이',
    karaoke: 'TJ',
  },
  {
    id: 'TJ_95882',
    title: '거짓말',
    number: '95882',
    singer: '연하남쓰',
    karaoke: 'TJ',
  },
  {
    id: 'TJ_97375',
    title: '거짓말처럼',
    number: '97375',
    singer: '치즈',
    karaoke: 'TJ',
  },
  {
    id: 'TJ_97216',
    title: '거짓사랑',
    number: '97216',
    singer: '나도희',
    karaoke: 'TJ',
  },
];
